### ISSUE TITLE
Picture not displayed

### ISSUE THREAD

**Issue by fllesser** [AjaxFNC-YT/Py-ItemShop#2]
![Screenshot_20241210_135134_com.microsoft.emmx_edit_44517674261434.jpg](https://github.com/user-attachments/assets/1502d6bb-710a-43b1-905b-b498bbe0f365)

**Comment by AjaxFNC-YT** [comment]
my API broke a while ago, and i just never fixed it..

**Comment by AjaxFNC-YT** [comment]
The API is on my github profile, if you want to fix it and make a PR
